### PR TITLE
Use string cmp instead of regex; simplify use of for select loop.

### PR DESCRIPTION
**Pull request by dullgiulio**
First change is really a performance improvement; the second is style only (I think.)

### CODE REVIEW

**Comment by dullgiulio** [comment]
No problem, feel free to make your own patch :)

**Comment by chillum** [comment]
OK, thanks. Can I post it from your name?

**Comment by dullgiulio** [comment]
Well sure, but no need to bother!

**Comment by chillum** [comment]
Thanks, merged your commit (the string cmp part) to https://github.com/chillum/httpstress-go

I hope, you're not affected by the thing, I moved this library development to the CLI tool repo. I think now, hardly anyone would want this as Go API, but the common repo makes releases easier. If I'm wrong, drop me a note.

Thanks again!

**Pull request merged**
